install_libraries<- function() {
  
  #specify the packages of interest
  packages = c("magrittr","tibble","dplyr","purrr", "ggplot2", "grDevices")
  
  #use this function to check if each package is on the local machine
  #if a package is installed, it will be loaded
  #if any are not, the missing package(s) will be installed and loaded
  package.check <- lapply(packages, FUN = function(x) {
    if (!require(x, character.only = TRUE)) {
      install.packages(x, dependencies = TRUE)
      library(x, character.only = TRUE)
    } else(
      library(x, character.only = TRUE)
    )
  })
  
}

# ----------------------------
# information function for a single item
inf.item <-function(x) (exp(x-b)/(1+exp(x-b)))*(1-(exp(x-b)/(1+exp(x-b))))

# ----------------------------
# tests information function
inf.test <-function(x,b) {
  sum((exp(x-b)/(1+exp(x-b)))*(1-(exp(x-b)/(1+exp(x-b)))))
}

# ----------------------------
#  test score function
test.curve <-function(x,b) {
  sum(exp(x-b)/(1+exp(x-b)))
}


# ----------------------------
#  test score function

multi_join <- function(list_of_loaded_data, join_func, ...){
  
  require("dplyr")
  
  output <- Reduce(function(x, y) {join_func(x, y, ...)}, list_of_loaded_data)
  
  return(output)
}

# ----------------------------
score_a_test<-function(round, item.params){

  ability <-seq(-6, 6, by = 0.01)
  
  test.scores<-sapply(ability,test.curve,item.params)
  
  tbl<- cbind(data.frame(ability),test.scores,round) %>%
    as_tibble()
  
  tbl$round <- as.character(tbl$round)
  
  tbl
}

# ----------------------------



# ----------------------------
get_plot_style<-function(testlets,style,main_tcc){
  #the main TCC
  main_TCC<-as.character(main_tcc)
  
  #all headings
  headings<- testlets
  
  #all other Grey TCC headings
  plot_TCC_headings<- headings[grepl("round",headings)]
  plot_TCC_headings<- plot_TCC_headings[plot_TCC_headings != main_TCC]
  
  #all other coloured TCC headings
  plot_coloured_headings<- headings[!grepl("round",headings)]
  plot_coloured_headings<- plot_coloured_headings[plot_coloured_headings != main_TCC]
  
  #need to sort colour
  if(style=="colours"){
    # colored lines  for next stage testlets
    cbPalette<-rainbow(length(plot_coloured_headings))
    names(cbPalette) <- plot_coloured_headings
    
    # grey lines for comparison TCCs
    cbGrey<-grey.colors(n = length(plot_TCC_headings), start = 0.4, end = 0.7)
    names(cbGrey) <- plot_TCC_headings
    
    
    # black lines for "main" TCCs
    cbGrey[main_TCC]<-"black"
    
    #merge all colours togerther
    return(c(cbGrey,cbPalette))
  }
  
  if(style=="linetype"){
    
    # colored lines  for next stage testlets
    linetype_testlest <- rep("solid", times= length(plot_coloured_headings))
    names(linetype_testlest) <- plot_coloured_headings
    
    # grey lines for comparison TCCs
    linetype_TCC <- rep("dashed", times= length(plot_TCC_headings))
    names(linetype_TCC) <- plot_TCC_headings
    
    # black lines for "main" TCCs
    linetype_TCC[main_TCC]<-"solid"
    
    return(c(linetype_TCC,linetype_testlest))
  }
  
  if(style=="size"){
    
    # colored lines  for next stage testlets
    size_testlest <- rep(1, times= length(plot_coloured_headings))
    names(size_testlest) <- plot_coloured_headings
    
    # grey lines for comparison TCCs
    size_TCC <- rep(.8, times= length(plot_TCC_headings))
    names(size_TCC) <- plot_TCC_headings
    
    # black lines for "main" TCCs
    size_TCC[main_TCC]<-1.3
    
    return(c(size_TCC,size_testlest))
  }
}

#----------------------------
# Make Token/ID
#----------------------------
# this token is used to link each iteration of ideal data to its output
# this token id is used to name all output generated by this ideal data.
# if new ideal data is used, create a new token
set_token<-function(){
  format(Sys.time(), "%Y-%m-%d %H.%M.%S")
}

get_token<-function(){
  Token
}

# ----------------------------

# ----------------------------
create_plot<-function(plot_data, round, level, dir="Output_Charts"){
  
  if(!dir.exists(file.path(dir))) {
    dir.create(file.path(dir))
  }
  filename<- paste0(dir, "/", level,"-",round," (", get_token() ,").png")
  
  drawn_plot<-draw_plot(plot_data,level)
  
  ggsave(filename, plot=drawn_plot, width = 20, height = 15, units = "cm")
  
  archive_data(results)
}

# ----------------------------
# Plots
draw_plot<-function(plot_data,level){
  #multi_join(results$test_scores, full_join )
  require(ggplot2)
  
  # active round
  active<-unique(plot_data$round)
  
  #remove comparative data
  comparative_tccs<- unique(plot_data$round)
  comparative_tccs<-comparative_tccs[comparative_tccs != active]
  
  
  #need to get colour and style
  plot_colours<-get_plot_style(unique(plot_data$round), style="colours",active)
  plot_colours<-unname(plot_colours[order(names(plot_colours))])
  plot_linetype<-get_plot_style(unique(plot_data$round), style="linetype",active)
  plot_size<-get_plot_style(unique(plot_data$round), style="size",active)
  
  
  
  
  
  active_plot<-  ggplot(plot_data, aes(x = plot_data$ability))  + 
    # theme_bw()+
    #### plot information curves grouped by testlet factor. Colour & grey
    geom_line(
      aes(  y=plot_data$test.scores,
            colour = plot_data$round,
            linetype=plot_data$round,
            group=plot_data$round
      ),
      size=2
    ) +
    ### legend
    scale_color_manual(name="Information",values="red")  +
    scale_linetype_manual(name="Information",values=plot_linetype) +
    scale_size_manual(name="Information", values=plot_size, guide = guide_legend(override.aes = list(
      #   linetype = plot_linetype,
      #   colours = plot_colours,
      size = plot_size)))  +
    #### add X axis label
    scale_x_continuous( expand = c(0.0, 0),name="Ability", limits = c(-6, 6)) +
    #### add Y axis label & grid
    scale_y_continuous(breaks=c(seq(0,max(plot_data$test.scores)+5,by=2)),expand = c(0.0, 0),name = "Test score") +
    #### add heading
    labs(title = paste(toupper(level)," ",toupper(active)))+
    # change size of legend key
    guides( linetype=guide_legend(keywidth = 2, keyheight = 1),
            colour=guide_legend(keywidth = 2, keyheight = 1)) #+
  
  
  
  return(active_plot)
}


# ----------------------------
# Archive Data
archive_data <- function(results, dir = "Archived_data") {
  
  if(!dir.exists(file.path(dir))) {
    dir.create(file.path(dir))
  }
  
  fname_prefix <- paste("Archived_Data", sep = "", collapse = "")
  
  fname <- paste(dir, "/",
                 fname_prefix, 
                 " ( ", get_token(), " )",
                 ".RData", 
                 sep = "", 
                 collapse = "")
  
  #file export
  save(results, file = fname)
  
} 

