---
title: "Compare Images"
author: ""
date: ""
output: 
  #http://rmarkdown.rstudio.com/flexdashboard/layouts.html
  flexdashboard::flex_dashboard:
    orientation: columns 
    vertical_layout: fill
    theme: paper  #cerulean  #journal  #flatly #  readable # spacelab  #paper


runtime: shiny

---
<!-- set up -->

```{r setup, include=FALSE}
library("shiny")
library("flexdashboard")
library("DT")
library("plotly")
library("tidyverse")
library("magrittr")
knitr::opts_chunk$set(echo = TRUE)
```

```{r global, include=FALSE}
# load data in 'global' chunk so it can be shared by all users of the dashboard
library(datasets)
#data(all_images)
```

```{r input_params, echo=FALSE}
 # create list of all the charts
 # use filenames to seperate information
 chart_directory <- "Output_Charts/"
 all_images<-tibble(fname = list.files(chart_directory, 
                                      "*.png", full.names = F))

 all_images<-{all_images%>%
    mutate(
      level=substr(.$fname, 1, regexpr('-', .$fname)-1) ,
      round=substr(.$fname, regexpr('-', .$fname)+1, regexpr(' ', .$fname)-1) ,
      directory=chart_directory,
      data_token=case_when(
        grepl("\\(",.$fname) ~ substr(.$fname, regexpr('\\(', .$fname)+1, regexpr('\\)', .$fname)-1) ,
        TRUE ~ "-")
    ) } %>%
  arrange(.$level, .$round, desc(.$data_token))


 all_rounds<-unique(all_images$round)
 all_levels<-unique(all_images$level)

```

Inputs {.sidebar data-width=300}
-----------------------------------------------------------------------
Use the options below to select a test.
```{r inputs_top, eval=TRUE, echo=FALSE}

#part 1 - Level & Round
inputPanel(
      selectInput("level", "Choose a level:",
                   choices = all_levels ),
      
      selectInput("round", "Choose a test:",
                   choices = all_rounds )
      )



#part 1.1 - get user input
selected_level<-reactive({input$level})
selected_round<-reactive({input$round})
selected_dyp<- reactive({unique(all_images[all_images$round==input$round &
                                             all_images$level==input$level ,])})
output$selected_round<-renderText({selected_round()})
output$selected_level<-renderText({selected_level()})


#part 2 - time range
all_times<-reactive({unique(all_images[all_images$round==input$round &
                                             all_images$level==input$level, ]$data_token)})

renderUI(inputPanel(
     sliderInput("time", 
             label = div(style='float:left;', 'Age of file',
                         div(style='width:200px;', 
                           div(style='float:left;', 'oldest'), 
                           div(style='float:right;', 'newest'))),
                    min = 1,
                    max = length(all_times()),
                    value = length(all_times()),step=-1, ticks = F, animate = T, width = '500px'
        )
  ))
  
#part 2.1- get user input time
selected_time<-reactive({
  length(all_times())+1 -input$time
  })

selected_fname<-reactive({
    selected_dyp()[selected_time(),]$fname
})
  
output$selected_time<-renderText({selected_time()})
output$selected_fname<-renderText({selected_fname()})
```


Column  {.tabset}
-------------------------------------

### Charts 
```{r charts, echo=FALSE}

#part 3- get plot based on all the user input

firstimagepath<-reactive({all_images[1,]$fname})

imagepath<-reactive({
    paste0(selected_dyp()[selected_time(),]$directory,selected_dyp()[selected_time(),]$fname)
    })
  
suppressWarnings(
    
  output$plot<-renderImage({
  
    out <- tryCatch(
      {if(file.exists(imagepath())){
              imagepath()
        }
        },
      error=function(cond) {
       # Choose a return value in case of error
       return(firstimagepath())
     },
     warning=function(cond) {
         # Choose a return value in case of error
       return(firstimagepath())
     }
    )
   
   list(src = out,
            contentType = 'image/png',
            width = 600,
            height = 500,
            alt = "This is alternate text")
   
 }, deleteFile = FALSE)
 )
 
```
> File: `r textOutput("selected_fname")`

`r  imageOutput("plot") `


### Files

```{r files, echo=FALSE}

#part 4- list of files  

all_files<-reactive({all_images[all_images$round==input$round &
                                             all_images$level==input$level, ]})

output$selected_all_files <- DT::renderDataTable({
 
    no_files<-data.frame(comment=c("No files found"))
  tryCatch(
    { 
      if (nrow(all_images)>0){
        
        hold_files<- all_files()
        hold_files<- DT::datatable(hold_files, 
                                         options = list(lengthMenu = c(100, 30, 50),
                                                        pageLength = 10,
                                                        scrollY = '600px',
                                                        scrollX = '300px',
                                                        paging = TRUE
                                                      ))
        }
 
      },
    error=function(cond) {
      # Choose a return value in case of error
      return(no_proportions)
    },
    warning=function(cond) {
        # Choose a return value in case of error 
      return(no_proportions)

    }
   )
  })

```
`r DT::dataTableOutput('selected_all_files')`

### Item Thresholds

Under construction
```{r thresholds, echo=FALSE}
 
#part 4- load threshold from archived data
suppressWarnings(

first_threshold<-reactive({ 
   directory <- "Archived_data/"
   thresh<-list.files(directory, "*.RData", full.names = T)[1] 
 
 substr(thresh, 
       regexpr('\\(', thresh)+1, 
       regexpr('\\)', thresh)-1) 
 })
)

suppressWarnings(
  threshold_timestamp<-reactive({ 
  
  # real archived data to match selection  criteria
  timestamp <-tryCatch(
    {
      selected_dyp()[selected_time(),]$data_token
    }
    ,error=function(cond){
      first_threshold()

    },warning=function(cond){
      first_threshold()
    }
  )
  timestamp
  })
  
)
suppressWarnings(
thresholds<-reactive({ 
  
 #   substr(selected_fname(), regexpr('\\(', selected_fname())+2, regexpr('\\)', selected_fname())-2) 
 # timestamp <-"2018-03-15 19.45.58" 
  fname <- paste('Archived_data/Archived_Data ( ',timestamp()," ).RData", sep="")

 loaded_threshold<- tryCatch(
      {if(file.exists(fname)){
             get(load(fname))
        }
        },
      error=function(cond) {
       # Choose a return value in case of error
        get(load(fname))
        },
     warning=function(cond) {
         # Choose a return value in case of error
        get(load(fname))
     }
    )

  loaded_threshold
  
})
)
suppressWarnings(

output$thresholds <- DT::renderDataTable({
 
    selected_round<-input$round
    selected_level<-input$level
    
    threshold <- thresholds()%>%
                   filter(.$round==selected_round)%>%
                   select(itm_params)
     
    t(t(unlist(threshold)))
     
  })
)
```
`r  DT::dataTableOutput('thresholds')`
